### ISSUE TITLE
No index.js

### ISSUE THREAD

**Issue by jonwalstedt** [GrafGenerator/gulp-json-server#10]
When i do a npm install --save-dev gulp-json-srv and try to use the package i get: "Error: Cannot find module 'gulp-json-srv'". When I view the package in the node_modules folder it seems like there is no index.js file. Is something wrong with the latest npm release?

**Comment by GrafGenerator** [comment]
@jonwalstedt seems to be a spontaneous issue with `npm pack`. Published hotfix v0.1.1, seems to be working now. Thanks for pointing out!
