### ISSUE TITLE
Custom routes not working

### ISSUE THREAD

**Issue by bdesilva-appneta** [GrafGenerator/gulp-json-server#17]
Hi, when I try to insert custom routes to the gulp json server using any of the following methods:

`const apiServer = jsonServer.start({
  data: 'test/mock-data/db.json',
  customRoutes: {
    '/api/': '/',
    '/blog/:resource/:step/show': '/:resource/:step'
  },
  port: 9000
});`

`const apiServer = jsonServer.start({
  data: 'test/mock-data/db.json',
  customRoutes: 'test/mock-data/routes.json',
  port: 9000
});`

I get this error:
`/Users/admin/Development/workspace/newapplication/webapplication/ui/node_modules/gulp-json-srv/index.js:50
                server[customRoute.method.toLocaleLowerCase()](path, customRoute.handler);
                                         ^

TypeError: Cannot read property 'toLocaleLowerCase' of undefined`

I would like to setup custom routes, so can you please help me with this?

Thanks,
Ben.

**Comment by GrafGenerator** [comment]
Hi,

I think you misunderstood customRoutes option, for me it seems that you need to use rewriteRules, not customRoutes. In your case it throws error because you're not specified request method and handler for custom route.
