### ISSUE TITLE
Update json file

### ISSUE THREAD

**Issue by courgette** [GrafGenerator/gulp-json-server#18]
Hi,

(sorry for my english)
I have a gulp task to serve my json file into my folder /datas/data.json and when i start gulp and add some datas, all work well. I stopped my gulp task, open /datas/data.json and all datas added are gone. There is an option to save my data into my static file ? 

Thanks you

**Comment by GrafGenerator** [comment]
@courgette 
There is no option to do that now, gulp-json-srv creates in-memory db when reads files from gulp pipeline. As a workaround for this you can use router object of json-server to access whole DB object. F.e. like this:

``` js
var jsonServer = require("gulp-json-srv");
var server = jsonServer.create();

var dbObj = server.router.db.getState(); // <-- this will give you whole DB at the moment
```

I understand now that this is the use case that I missed, and saving data back to file is good, I think it's candidate for feature request.

**Comment by GrafGenerator** [comment]
Created #19 for feature request.

**Comment by GrafGenerator** [comment]
@courgette Also notice that for example above `server.router` will ba available after server started (i.e. first file went though pipeline).

**Comment by courgette** [comment]
Ok thank you. 

The watch task work only on the static file right ? not in datas into the application.

**Comment by GrafGenerator** [comment]
@courgette I'm afraid I don't understood your question right, but anyway, `watch` task will be watching any file you'll set it to watch and reload server accordingly:) See [samples.md](https://github.com/GrafGenerator/gulp-json-server/blob/master/SAMPLES.md) for examples of watch task, and reloading server from object, not file.

**Comment by courgette** [comment]
Ok thank you, i try that.
