### ISSUE TITLE
Add ability to integrate into gulp pipeline

### ISSUE THREAD

**Issue by GrafGenerator** [GrafGenerator/gulp-json-server#8]
Implement integration into gulp's pipeline, wmth like this:

``` js
gulp.src(['somefile.json']).pipe(jsonServer.pipe());
```

**Comment by edm00se** [comment]
+1

This would be quite handy.

**Comment by GrafGenerator** [comment]
@edm00se already in progress, will be soon:)

**Comment by reintroducing** [comment]
@GrafGenerator Has this been added? I see your "will be soon" comment was in Nov 11, 2015 so just wondering if you were able to make progress on this. Thanks.

**Comment by edm00se** [comment]
Based on [the feature branch](https://github.com/GrafGenerator/gulp-json-server/tree/feature/gulp-pipeline-integration?files=1) out there, it looks like not yet.

**Comment by GrafGenerator** [comment]
@reintroducing feature still unfinished, haven't time to do this. Feature branch that @edm00se pointed contains almost working AFAIR, but there is one bug (remember that it was, but don't remember what exactly was), and also tests unfinished. I will try to finish this one within next 2-3 weeks, if you need it, you may use version from feature branch, but at your own risk:)

**Comment by GrafGenerator** [comment]
Feature development done, need to update the documentation and samples. Expected to be released in v1.0.0 this weekend.

**Comment by GrafGenerator** [comment]
Just released. v1.0.0 contains breaking changes, be careful:)
